---
booktitle: Proceedings of the Geometry-grounded Representation Learning and Generative
  Modeling Workshop (GRaM)
shortname: GRaM Workshop
volume: '251'
year: '2024'
start: &1 2024-07-29
end: 2024-07-29
published: 2024-10-12
conference_number: '1'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: gram24
month: 0
cycles: false
bibtex_editor: Vadgama, Sharvaree and Bekkers, Erik and Pouplin, Alison and Kaba,
  Sekou-Oumar and Walters, Robin and Lawrence, Hannah and Emerson, Tegan and Kvinge,
  Henry and Tomczak, Jakub and Jegelka, Stephanie
editor:
- given: Sharvaree
  family: Vadgama
- given: Erik
  family: Bekkers
- given: Alison
  family: Pouplin
- given: Sekou-Oumar
  family: Kaba
- given: Robin
  family: Walters
- given: Hannah
  family: Lawrence
- given: Tegan
  family: Emerson
- given: Henry
  family: Kvinge
- given: Jakub
  family: Tomczak
- given: Stephanie
  family: Jegelka
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Geometry-grounded Representation Learning and Generative Modeling Workshop (GRaM)
    Held in Vienna, Asutria on 29 July 2024

  Published as Volume 251 by the Proceedings of Machine Learning Research on 12 October 2024.

  Volume Edited by:
    Sharvaree Vadgama
    Erik Bekkers
    Alison Pouplin
    Sekou-Oumar Kaba
    Robin Walters
    Hannah Lawrence
    Tegan Emerson
    Henry Kvinge
    Jakub Tomczak
    Stephanie Jegelka

  Series Editors:
    Neil D. Lawrence
date_str: 29 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v251"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v251
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v251
email: ''
conference:
  name: Geometry-grounded Representation Learning and Generative Modeling Workshop
    (GRaM) at ICML 2024
  url: https://openreview.net/group?id=ICML.cc/2024/Workshop/GRaM
  location: Vienna, Asutria
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v251/gram24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v251/gram24.bib
